---
title: "Problem 1"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(haven)
library(dplyr)
library(tidyr)
library(knitr)
library(ggridges)
library(ggthemes)
library(stringr)
library(viridis)
library(plotly)
library(hexbin)
library(httr)
library(jsonlite)
library(forcats)
library(tidytext)
```

```{r, load and clean data, include = FALSE, cache=TRUE}
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
          )
      ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/9w7m-hzhe.json"

nyc_inspections = get_all_inspections(url) %>%
  bind_rows()

nyc_inspections = janitor::clean_names(nyc_inspections)

nyc_inspections$score <- as.numeric(nyc_inspections$score)
nyc_inspections$score <- as.integer(nyc_inspections$score)

# Create mean score column by boro
nyc_inspections <- nyc_inspections %>%
  group_by(boro) %>%
  mutate(mean_score_boro = mean(score, na.rm = TRUE))

# Subset to bakeries only
bakery_inspec <- nyc_inspections [ which(nyc_inspections$cuisine_description == 'Bakery'), ]

# Create mean score column by boro
bakery_inspec <- bakery_inspec %>%
  group_by(zipcode) %>%
  mutate(mean_score_zip = mean(score, na.rm = TRUE))
```

Column {data-width=550}
-----------------------------------------------------------------------

### Chart A

```{r, echo = FALSE}
<<<<<<< HEAD
bakery_inspec %>%
  group_by(zipcode) %>%
  mutate(zipcode = reorder(zipcode, score))
  plot_ly(x = ~bakery_inspec$zipcode, y = ~bakery_inspec$score, color =  
            bakery_inspec$zipcode, type = "bar")
  
bakery_inspec %>%
  group_by(zipcode) %>%
  mutate(zip = fct_reorder(zipcode, score))
  plot_ly(x = ~zip, y = ~bakery_inspec$score, color =  
            bakery_inspec$zipcode, type = "bar")
=======
# bakery_inspec %>%
 group_by(zipcode) %>%
  mutate(zipcode = reorder(zipcode, score)) %>%
  plot_ly(x = ~bakery_inspec$zipcode, y = ~bakery_inspec$score, color  = bakery_inspec$zipcode, type = "bar")
>>>>>>> 20ef715c2c0ed27fd57e0bd9d540b8816725ceb2
```

Column {data-width=225}
-----------------------------------------------------------------------

### Chart B

```{r}
box_ggplot =
  bakery_inspec %>%
  mutate(boro = fct_reorder(boro, score)) %>%
  ggplot(aes(x = boro, y = score, fill = boro)) +
  geom_boxplot() +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(box_ggplot)
```

### Chart C

```{r}
# number critical, not critical, etc
# criticaln<-nyc_inspections %>%
#   filter(boro != "Missing") %>% 
#   ggplot(aes(x = boro, fill = critical_flag)) + 
#   geom_bar()
# 
# ggplotly(criticaln)

### another way? ###
# nyc_inspections %>%
#   filter(boro != "Missing") %>% 
#   plot_ly(x = ~boro, y=~score, color = ~critical_flag, type = "bar")
# 
nyc_inspections %>%
  filter(boro != "Missing") %>%
  plot_ly(y=~score, color = ~boro, type = "box")


##is this even interesting?##

# nyc_inspections %>%
#   filter(boro != "Missing") %>% 
#   plot_ly(x = ~boro, y=~zipcode, color = ~critical_flag, type = "scatter")

```

Column {data-width=225}
-----------------------------------------------------------------------

### Chart D

```{r}
count number per grade per boro
nyc_inspections %>%
  filter(boro != "Missing") %>%
  filter(grade %in% c("A", "B", "C")) %>%
  plot_ly(x = ~boro, y=~score, color = ~grade, type = "bar")


#something with sentiments?
```

