---
title: "Problem 2"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
runtime: shiny
---

```{r setup, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(haven)
library(dplyr)
library(tidyr)
library(knitr)
library(ggridges)
library(ggthemes)
library(stringr)
library(viridis)
library(plotly)
library(hexbin)
library(httr)
library(jsonlite)
library(forcats)
library(tidytext)
library(shiny)
```


```{r, load csv, include = FALSE}
# Load csv of subsetted data
bakery_inspec = read.csv("bakery_inspec.csv")
bakery_inspec$score <- as.numeric(bakery_inspec$score)
```

Column {.sidebar}
-----------------------------------------------------------------------
This `flexdashboard` with Shiny was made for Homework 6 of [Jeff Goldsmith's Data Science I class](http://jeffgoldsmith.com/DSI/homework_6.html) in the Department of Biostatistics at Columbia University. It was created by [Kaitlin Maciejewski](https://github.com/k-maciejewski) and [Rebecca Venetianer](https://github.com/rvenetianer).


```{r widgets}

boros = bakery_inspec %>% distinct(boro) %>% pull()

# selectInput widget
selectInput("boro_choice", label = h3("Select Borough"),
            choices = boros, selected = "Manhattan")

hr()

renderUI({
  
# set min and max hour of the day
min_score = bakery_inspec %>% filter(boro == input$boro_choice) %>% select(score) %>% filter(!is.na(score)) %>%  min()

max_score = bakery_inspec %>% filter(boro == input$boro_choice) %>% select(score) %>% filter(!is.na(score)) %>%  max()

# sliderInput widget
sliderInput("score_choice", label = h3("Choose score"), min = min_score, 
        max = max_score, value = c(0, 93), step = 1)

})

hr()

# zipcode = bakery_inspec %>% distinct(zipcode) %>% pull()
# 
# # radioButtons widget
# radioButtons("Zipcode", label = h3("Choose zipcode"),
#     choices = zipcode, 
#     selected = "10011")
```

Row {.tabset .tabset-fade } 
-----------------------------------------------------------------------

### Inspection Scores Based on Inspection Type in Washington Heights and Inwood (Manhattan)

```{r}
renderPlotly({
  
  # Plot scores for WaHi/Inwood bakeries
bakery_inspec %>% filter(boro == input$boro_choice, score %in% input$score_choice[1]:input$score_choice[2]) %>%
  group_by(dba) %>%
  filter(zipcode %in% c("10031", "10032", "10033", "10034", "10040"), critical_flag == "Critical") %>% 
plot_ly(x = ~inspection_type, y = ~score, color = ~inspection_type, type = "bar")

})
```

### Bakeries with Critical Levels per Borough

```{r bar plot criticals in each boro}
renderPlotly({
  
  bakery_inspec %>%
  filter(boro != "Missing") %>% filter(boro == input$boro_choice, score %in% input$score_choice[1]:input$score_choice[2]) %>% 
  plot_ly(x = ~boro, y=~score, color = ~critical_flag, type = "bar")
  
})
```


### Inspection Score Distribution per Borough

```{r box plot score in each boro}
renderPlotly({
  
  bakery_inspec %>%
  filter(boro != "Missing") %>% filter(boro == input$boro_choice, score %in% input$score_choice[1]:input$score_choice[2]) %>% 
  plot_ly(y=~score, color = ~boro, type = "box")
  
})
```

